import 'package:flutter/material.dart';
import "package:rep_manager/themes/theme.dart";

const sampleData = [
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
  ["Iain Simpson", "BSc Software Engineering", "2nd"],
  ["Steph Lomas", "LLB Law", "Fdn"],
  ["Becky Best", "LLB Law", "2nd"],
  ["Krupa Raithatha", "BA Events Management", "3rd"],
  ["Hannah Mason", "BA Communication", "2nd"],
  ["Daisy Muir", "BA Fine Art", "2nd"],
  ["Ian Blease", "BA Managemet", "1st"],
  ["Liam Middleton", "BSc Web Development", "3rd"],
];

class repPage extends StatefulWidget {
  repPage({Key? key}) : super(key: key);

  List<int> selectedIndexes = [];
  
  bool focusSelected = false;
  int focusedIndex = 0;

  @override
  State<repPage> createState() => _repPageState();
}

class _repPageState extends State<repPage> {
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
  }

  @override
  Widget build(BuildContext context) {

    Icon addNewRepIcon = const Icon(Icons.add, color: textColor,);
    Icon editRepDetailsIcon = const Icon(Icons.edit, color: textColor,);
    Icon addRepToGroupIcon = const Icon(Icons.drive_file_move);
    Icon downloadRepInformationIcon = const Icon(Icons.download);
    Icon deleteRepIcon = const Icon(Icons.delete);

    bool? checkedValue = false;

    if (widget.selectedIndexes.length > 1) {
      editRepDetailsIcon = const Icon(
        Icons.edit,
        color: Color.fromARGB(100, 0, 0, 0),
      );
    }
    else {
      editRepDetailsIcon = const Icon(
        Icons.edit,
        color: textColor,
      );
    }

    int focusBoxHeight = 0;
    Container focusBox = Container(height: 0);
    if (widget.focusSelected) {
      focusBoxHeight = 350;
      focusBox = Container(
        height: 350,
        width: MediaQuery.sizeOf(context).width - 400,
        decoration: const BoxDecoration(
          color: bodyColor,
          border: Border(
            top: BorderSide(width: 1, color: Colors.black),
          ),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const SizedBox(height: 10),
            Row(children: [
              const SizedBox(width: 10,),              
              GestureDetector(
                child: const Icon(Icons.close, size: 15,),
                onTap: () {
                  setState(() {
                    widget.focusSelected = false;
                  });
                },
              )
            ],),
            const SizedBox(height: 15,),
            Row(children: [
              const SizedBox(width: 35),
            
            
              // Rep Information
              Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  //const SizedBox(height: 35),
                  Text(sampleData[widget.focusedIndex][0], style: h3,),
                  Text(sampleData[widget.focusedIndex][1], style: paragraph,),
                  const SizedBox(height: 20),
                  Row(
                    children: [
                      Column(
                        crossAxisAlignment: CrossAxisAlignment.end,
                        children: [
                          Text("G Number:", style: paragraph,),
                          Text("Email:", style: paragraph,),
                          Text("Mode:", style: paragraph,),
                          Text("Campus:", style: paragraph,),
                          Text("Level:", style: paragraph,),
                          Text("Start Date:", style: paragraph,),
                          Text("End Date:", style: paragraph,),
                        ],
                      ),
                      const SizedBox(width: 10,),
                      Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text("G21002528", style: paragraph,),
                          Text("isimpson3@uclan.ac.uk", style: paragraph,),
                          Text("FT", style: paragraph,),
                          Text("Preston", style: paragraph,),
                          Text("UG", style: paragraph,),
                          Text("1/7/24", style: paragraph,),
                          Text("1/7/25", style: paragraph,),
                        ],
                      ),
                    ],
                  ),
                  const SizedBox(height: 20,),
                  Row(children: [
                    ElevatedButton(
                      style: ElevatedButton.styleFrom(
                        foregroundColor: Colors.white,
                        backgroundColor: Colors.black,
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(5.0),
                        ),
                      ), 
                      onPressed: () {
            
                      }, 
                      child: const Row(children: [ Icon(Icons.email), SizedBox(width: 10,), Text("Email") ])
                    ),
                    const SizedBox(width: 20,),
                    ElevatedButton(
                      style: ElevatedButton.styleFrom(
                        foregroundColor: Colors.white,
                        backgroundColor: Colors.red,
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(5.0),
                        ),
                      ),
                      onPressed: () {},
                      child: const Row(children: [Icon(Icons.delete), SizedBox(width: 5,), Text("Delete")]))
                  ],)
                ],
              )
            ]),
          ],
        ),
      );
    }

    String selectAllText = "Select All";
    Icon selectAllIcon = Icon(Icons.circle_outlined);
    if (widget.selectedIndexes.isNotEmpty) {
      selectAllText = "${widget.selectedIndexes.length} Selected";
      selectAllIcon = const Icon(Icons.circle, color: primaryColor,);
    }

    return Row(children: [
      //Side Bar
      Container(
        width: 400,
        height: MediaQuery.sizeOf(context).height - 75,
        decoration: BoxDecoration(
          color: secondaryColor,
          border: Border.all(color: Colors.black, width: 2),
        ),
        child: ListView(
          children: [
            CheckboxListTile(
                title: Text("title text"),
                value: checkedValue,
                onChanged: (newValue) {
                  setState(() {
                    checkedValue = newValue;
                  });
                },
                controlAffinity:
                    ListTileControlAffinity.leading, //  <-- leading Checkbox
              )
          ],
        ),
      ),

      //Content
      Column( children: [
        Container(
          width: MediaQuery.sizeOf(context).width - 400,
          height: 50,
          color: secondaryColor,
          child: Row(
            children: [
              const Padding(padding: EdgeInsets.fromLTRB(10, 0, 10, 0)),
              GestureDetector(
                child: addNewRepIcon,
                onTap: () {

                },
              ),
              const Padding(padding: EdgeInsets.fromLTRB(10, 0, 10, 0)),
              GestureDetector(
                  child: editRepDetailsIcon,
                  onTap: () {
                    if (widget.selectedIndexes.length > 1)
                    {
                      // Do nothing if more than 1 person is selected
                    }
                    else {
                      // All code goes here
                    }
                  },
                ),
              const Padding(padding: EdgeInsets.fromLTRB(10, 0, 10, 0)),
              GestureDetector(
                  child: addRepToGroupIcon,
                  onTap: () {},
                ),
              const Padding(padding: EdgeInsets.fromLTRB(10, 0, 10, 0)),
              GestureDetector(
                  child: downloadRepInformationIcon,
                  onTap: () {},
                ),
              const Padding(padding: EdgeInsets.fromLTRB(10, 0, 10, 0)),
              GestureDetector(
                  child: deleteRepIcon,
                  onTap: () {},
                ),
              const Expanded(child: SizedBox()),
              GestureDetector(
                child: selectAllIcon,
                onTap: () {
                  if (widget.selectedIndexes.isEmpty) {
                    setState(() {
                      for (int i = 0; i < sampleData.length; i++) {
                        widget.selectedIndexes.add(i);
                      }
                    });
                  }
                  else {
                    setState(() {
                      widget.selectedIndexes.clear();
                    });
                  }
                },
              ),
              const Padding(padding: EdgeInsets.fromLTRB(0, 0, 10, 0)),
              SizedBox(width: 120, child: Text(selectAllText, style: paragraph,)),
              const Padding(padding: EdgeInsets.fromLTRB(10, 0, 10, 0)),
            ]
          ),
        ),
        Container(
          width: MediaQuery.sizeOf(context).width - 400,
          height: MediaQuery.sizeOf(context).height - (125 + focusBoxHeight),
          child: ListView.builder(
            itemCount: sampleData.length,
            itemBuilder: (BuildContext context, int index) {

              Icon circleIcon = Icon(Icons.circle_outlined, color: textColor,);
              if (widget.selectedIndexes.contains(index)) { circleIcon = Icon(Icons.circle, color: primaryColor,); }

              return ListTile(
                leading: GestureDetector(
                  child: circleIcon,
                  onTap: () {
                    if (widget.selectedIndexes.contains(index)) {
                      setState(() {
                        widget.selectedIndexes.remove(index);
                      });
                    } else {
                      setState(() {
                        widget.selectedIndexes.add(index);
                      });
                    }
                  },
                ),
                title: Text(sampleData[index][0], style: paragraph,),
                trailing: Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Text(
                      sampleData[index][1],
                      style: paragraph, 
                    ),
                    const SizedBox(width: 20),
                    SizedBox(
                      width: 40,
                      height: 20,
                      child: Text(
                        sampleData[index][2],
                        style: paragraph,
                      ),
                    )
                  ],
                ),
                shape: ContinuousRectangleBorder(
                  side: const BorderSide(color: secondaryColor, width: 1),
                  borderRadius: BorderRadius.circular(5),
                ), 
                onTap: () {
                  setState(() {
                    widget.focusSelected = true;
                    widget.focusedIndex = index;
                  });
                },                
              );
            },
          )
        ),
        focusBox,
      ],)
    ],);
  }
}
