name: rephub
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  csv_localizations: ^1.7.0+4
  data_table_2: ^2.5.12
  flutter:
    sdk: flutter
  google_fonts: 6.1.0
  ios_receipt: ^1.0.0
  path_provider: ^2.1.3
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
